AWSTemplateFormatVersion: "2010-09-09"
Description: Create Parameters for pipeline
Parameters:
  Namespace:
    Description: Tag for the name of the product
    Type: String

Resources:
  GitHookSecret:
    Type: AWS::SecretsManager::Secret
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Description: Webhook secret for github integration
      GenerateSecretString:
        IncludeSpace: False
        PasswordLength: 64
        RequireEachIncludedType: True
      Name: !Sub "${Namespace}HookSecret"

  GitAccessToken:
    Type: AWS::SecretsManager::Secret
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      Description: GitHub access token for registering runners in the organization or repo
      Name: !Sub "${Namespace}GitToken"
      SecretString: '{"token":""}'

Outputs:
  GitHookSecret:
    Value: !Ref GitHookSecret
  GitAccessToken:
    Value: !Ref GitAccessToken
